global using System.Net;
global using NSubstitute;
global using NUnit.Framework;
global using Mel.DotnetWebService.CrossCuttingConcerns.ErrorHandling;
global using Mel.DotnetWebService.CrossCuttingConcerns.ExtensionMethods;
global using Mel.DotnetWebService.Tests.FearlessProgramming.ExtensionMethods;
global using Mel.DotnetWebService.Tests.FearlessProgramming.FrameworkExtension.Exceptions;
global using Mel.DotnetWebService.Tests.FearlessProgramming.FrameworkExtension.Serialization;
global using Is = Mel.DotnetWebService.Tests.FearlessProgramming.FrameworkExtension.NUnitCustomizations.Is;
global using Mel.DotnetWebService.Tests.FearlessProgramming.TestData.Archetypes;
global using Mel.DotnetWebService.Tests.FearlessProgramming.TestData.TestCases;
global using Mel.DotnetWebService.Tests.FearlessProgramming.TestEnvironments.TestDoubles;
global using Mel.DotnetWebService.Tests.FearlessProgramming.TestEnvironments.TestExecutionRuntime;
global using Mel.DotnetWebService.Tests.FearlessProgramming.TestEnvironments.TestServers;
global using Mel.DotnetWebService.Tests.FearlessProgramming.TestEnvironments.TestSpecificDataStructures;
