namespace Mel.DotnetWebService.Api.ExtensionMethods;

static class RuntimeValidatorExtensionMethods
{
	public static void EnsureThatConstrainedTypesInvolvedInControllerActionSignaturesCanBeDeserialized(this Concerns.RuntimeValidation.RuntimeValidator runtimeValidator)
	=> Concerns.DataValidity.Integration.ConstrainedTypes.Serialization.EnsureThatConstrainedTypesInvolvedInControllerActionSignaturesCanBeDeserialized(runtimeValidator);
	public static void EnsureThatEnumTypesInvolvedInsideControllerActionSignaturesCanBeDetectFailedOrSkippedDeserialization(this Concerns.RuntimeValidation.RuntimeValidator runtimeValidator)
	=> Concerns.EnumsHandling.Integration.FailedOrSkippedDeserializationDetection.Serialization.EnsureThatEnumTypesInvolvedInsideControllerActionSignaturesCanBeDetectFailedOrSkippedDeserialization(runtimeValidator);
}
